// Resolves `git describe` once at build/dev start and writes src/version.ts,
// so the running app never shells out to git (docs/CLAUDE.md, App versioning).
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";

let version = "unknown";
try {
  version = execSync("git describe --tags --long --always --dirty", {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
} catch {
  // No git or no repo: ship "unknown" rather than failing the build.
}

writeFileSync(
  new URL("../src/version.ts", import.meta.url),
  `// Generated by scripts/gen-version.mjs — do not edit, not committed.\n` +
    `export const VERSION = ${JSON.stringify(version)};\n`,
);
